### ISSUE TITLE
Finding substrings for long similar words takes a long time

### ISSUE THREAD

**Issue by kjlubick** [hanwencheng/CommonSubstrings#3]
I noted one of my use cases for this code had gotten quite slow with some specific input, so I benchmarked input to see if I could track down what is slow.

I compared 3 cases of data:

1. random strings of increasing length (increasing in length by 8 every time)
2. strings where the nth string is the n-1th string + 8 random characters
3. strings where the nth string is the n-1th string + " (retry)" [8 characters]

[code gist](https://gist.github.com/kjlubick/eb05d9667d6740db8d6f420c2d4ed66f)

All used the same params I had been using when I noticed the bottleneck:

```
var substrings = new Substrings({
    minOccurrence: Math.max(2, arr.length-1),
    minLength: 6,
});
```

Some examples of my benchmarking:

length = 8

1. 13ms ["abcdefghij", "efghijk", "ofMiGH4w84U4J06", "8cYmRMpijY5pHPyg1SSxVSz", "3LLjLQrOwo3OqMdSSsSjxtAaDtFP5PC", "0mJRz6na Vm7Orv8uLO8zuW0SN4X9eLuJBmOzQS", "V TVgBTXZgALmEhz5Lj148S06KHYNfuMr8kHgldqQmqhl2k", "FXlmCXDQDpBJ4BNfLmV3waxvYDw28MEFnwxOeKpjEMc MrFHRmFlHsi"]
2.  80ms ["abcdefghij", "efghijk", "efghijk0.935430", "efghijk0.9354300.348696", "efghijk0.9354300.3486960.071322", "efghijk0.9354300.3486960.0713220.224642", "efghijk0.9354300.3486960.0713220.2246420.894032", "efghijk0.9354300.3486960.0713220.2246420.8940320.871427"]
3.  70ms ["abcdefghij", "efghijk", "efghijk (retry)", "efghijk (retry) (retry)", "efghijk (retry) (retry) (retry)", "efghijk (retry) (retry) (retry) (retry)", "efghijk (retry) (retry) (retry) (retry) (retry)", "efghijk (retry) (retry) (retry) (retry) (retry) (retry)"]

length = 13 (examples omitted for brevity)

1. 36ms
2. 144000ms
3. 300000ms

Notice that even though the length of the strings is the same in each of the three cases, it seems that those strings that have more overlapping between strings take longer to parse, especially at the extreme case.

Is there a way to make commonSubstrings faster on these cases?  

I put some breakpoints in the find substrings code, and is there a chance that there is a chance to memoize some of the calls to findFragments?  I noticed there were possibly several calls that seemed to have the same params and perhaps that could be cached and reused for speed.

**Comment by heawen110** [comment]
Hi, @kjlubick , Thanks for reporting the problem, finally I got time to rewrite the code in [new algorithms](https://github.com/hanwencheng/CommonSubstrings/commit/e12a0dd5375c361f6ac7c0c4a1054f6f623a3ce7) . With both the speed the correctness improvement, the problem is resolved.

Now it has a good perfermance as follows.

<img width="503" alt="screen shot 2019-02-03 at 9 02 17 pm" src="https://user-images.githubusercontent.com/45123243/52184186-44c72380-2810-11e9-9d33-c2393fea9f14.png">

**Comment by hanwencheng** [comment]
Hi, @kjlubick , Thanks for reporting the problem, finally I got time to rewrite the code in [new algorithms](https://github.com/hanwencheng/CommonSubstrings/commit/e12a0dd5375c361f6ac7c0c4a1054f6f623a3ce7) . With both the speed the correctness improvement, the problem is resolved.

Now it has a good perfermance as follows.

<img width="503" alt="screen shot 2019-02-03 at 9 02 17 pm" src="https://user-images.githubusercontent.com/6014309/52184213-94a5ea80-2810-11e9-9ae2-c6dc12c72f25.png">
