### ISSUE TITLE
Trying to understand what the expected output should be

### ISSUE THREAD

**Issue by yaakov123** [hanwencheng/CommonSubstrings#4]
Hey there,

I'm trying to wrap my head around the results that I'm getting. In the Readme it says the following:

With the following input:
`['java', 'javascript','pythonscript']` 
I get the following output: 
`  [
    {name : 'java', source : [0,1], weight : 8},
    {name : 'script', source : [1,2], weight : 10}
  ]`

This works. However given the following input: 
`['java', 'javascript','pythonscript', 'andjavascript']`
I get the following output:
`[ { name: 'javascript', source: [ 1, 3 ], weight: 20 } ]`

Why don't I get the `java` and `script` results?

**Comment by yaakov123** [comment]
Additionally, would there be a way for me to get every common letter in each string so that I would get:
`j, ja, jav, etc.` as a result

**Comment by hanwencheng** [comment]
Hi, @yaakov123,

It is an expected behaviour that we do not want duplicate occurrence like `java` and `javascript` in your example. Here we will "digest" the short substrings' occurrence when we accumulate the longest common substrings occurrence[1]. 

As you pointed here you want the occurrence `j, ja, jav, etc.`, I guess to get them all are quite redundant, probably you want `java, script, javascript` to be listed at the same time in your example `['java', 'javascript','pythonscript', 'andjavascript']`. The most related code is here: https://github.com/hanwencheng/CommonSubstrings/blob/master/src/commonSubstrings.js#L187-L188. You may try to customize it for your desired output.

*[1]Another option is that we may `digest` the longer substrings to get the most occurrence of the short substrings. To achieve this, we need to start the `excludeDuplicateHorizontally` from the shortest substrings, which will need more refactoring work. Probably re-write the whole library.*
